seed: 1997
folds: [0, 1, 2, 3, 4]
train_batch_size: 32
valid_batch_size: 128
use_sampler: false
num_workers: 8
output_dir: "/home/romainlhardy/kaggle/rsna-abdominal-trauma/models/scan_classification/checkpoints"
wandb_project: "rsna-abdominal-scan-classification"

early_stopping:
  mode: "min"
  patience: 100
  verbose: 1

accumulate:
  scheduling: {0: 1}

swa:
  swa_lrs: 1.0e-2
  swa_epoch_start: 0.8

model:
  scheduler:
    num_warmup_steps: 200
    num_training_steps: 2000
  optimizer:
    lr: 2.0e-4
    betas: [0.9, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8
  model:
    time_dim: 128
    feature_dim: 2816
    hidden_dim: 64
    num_layers: 2
    dropout: 0.2
    bidirectional: true
  losses:
    alpha: 0.8
    prob_mixup: 0.5
    classification:
      any_injury:
        type: "ce"
        train_weight: [1.0, 12.0]
        valid_weight: [1.0, 6.0]
        label_smoothing: 0.0
      extravasation: 
        type: "ce"
        train_weight: [1.0, 12.0]
        valid_weight: [1.0, 6.0]
        label_smoothing: 0.0
      bowel:
        type: "ce"
        train_weight: [1.0, 4.0]
        valid_weight: [1.0, 2.0]
        label_smoothing: 0.0
      liver_injury:
        type: "ce"
        train_weight: [1.0, 4.0, 8.0]
        valid_weight: [1.0, 2.0, 4.0]
        label_smoothing: 0.0
      spleen_injury:
        type: "ce"
        train_weight: [1.0, 4.0, 8.0]
        valid_weight: [1.0, 2.0, 4.0]
        label_smoothing: 0.0
      kidney_injury:
        type: "ce"
        train_weight: [1.0, 4.0, 8.0]
        valid_weight: [1.0, 2.0, 4.0]
        label_smoothing: 0.0
    segmentation:
      organ:
        type: "bce"
        train_weight: 1.0
        valid_weight: 1.0
  data:
    time_dim: 128

trainer:
  min_steps: 2000
  max_steps: 2000
  max_epochs: 1000
  enable_progress_bar: false
  precision: "16-mixed"
  accelerator: "gpu"
  devices: 2
  strategy: "ddp_find_unused_parameters_false"