seed: 0
folds: [0, 1, 2, 3, 4]
train_batch_size: 64
valid_batch_size: 64
use_sampler: true
num_workers: 8
output_dir: "/home/romainlhardy/kaggle/rsna-abdominal-trauma/models/slice_classification/checkpoints"
wandb_project: "rsna-abdominal-slice-classification"

early_stopping:
  mode: "min"
  patience: 100
  verbose: 1

accumulate:
  scheduling: {0: 1}

swa:
  swa_lrs: 1.0e-2
  swa_epoch_start: 0.8

model:
  scheduler:
    num_warmup_steps: 500
    num_training_steps: 12000
  optimizer:
    lr: 4.0e-5
    betas: [0.9, 0.999]
    weight_decay: 1.0e-5
    eps: 1.0e-8
  model:
    class: SliceClassificationModel
    encoder_name: "convnextv2_tiny.fcmae_ft_in22k_in1k_384"
    params:
      dropout: 0.2
      backbone_params: 
        pretrained: true
        in_chans: 4
        drop_path_rate: 0.2
  losses:
    alpha: 0.8
    prob_mixup: 0.5
    classification:
      any_injury:
        type: "ce"
        train_weight: [1.0, 12.0]
        valid_weight: [1.0, 6.0]
        label_smoothing: 0.1
      extravasation: 
        type: "ce"
        train_weight: [1.0, 12.0]
        valid_weight: [1.0, 6.0]
        label_smoothing: 0.1
      bowel:
        type: "ce"
        train_weight: [0.5, 1.0, 4.0]
        valid_weight: [0.5, 1.0, 2.0]
        label_smoothing: 0.1
      liver_injury:
        type: "ce"
        train_weight: [0.5, 1.0, 4.0, 8.0]
        valid_weight: [0.5, 1.0, 2.0, 4.0]
        label_smoothing: 0.1
      spleen_injury:
        type: "ce"
        train_weight: [0.5, 1.0, 4.0, 8.0]
        valid_weight: [0.5, 1.0, 2.0, 4.0]
        label_smoothing: 0.1
      kidney_injury:
        type: "ce"
        train_weight: [0.5, 1.0, 4.0, 8.0]
        valid_weight: [0.5, 1.0, 2.0, 4.0]
        label_smoothing: 0.1
    segmentation:
      organ:
        type: "bce"
        train_weight: 1.0
        valid_weight: 1.0
  data:
    image_size: 384
    num_channels: 3

trainer:
  min_steps: 12000
  max_steps: 12000
  max_epochs: 1000
  enable_progress_bar: false
  precision: "16-mixed"
  accelerator: "gpu"
  devices: 2
  strategy: "ddp_find_unused_parameters_false"